### ISSUE TITLE
Container signature missing BinarySignatures

### ISSUE THREAD

**Issue by paulyoung84** [peterjohnlawrence/pronom2020#4]
The container signature does not contain any BinarySignature sequences, so any formats including these are failing in DROID. See example attached.
[example (1).txt](https://github.com/peterjohnlawrence/pronom2020/files/4394905/example.1.txt)

**Comment by peterjohnlawrence** [comment]
That's an issue that def needs investigating

**Comment by peterjohnlawrence** [comment]
Fixed, except when a signature has two or more subsequences: This is what is generated:

```
<ContainerSignature Id="9000" ContainerType="ZIP">
   <Description>Open Document Database 1.0</Description>
   <Files>
      <File>
         <Path>META-INF/manifest.xml</Path>
         <BinarySignatures>
            <InternalSignatureCollection>
               <InternalSignature Id="322">
                  <ByteSequence Reference="Absolute from BOF">
                     <SubSequence Position="1" SubSeqMaxOffset="1024" SubSeqMinOffset="0">
                        <Sequence>'manifest:media-type="application/vnd.oasis.opendocument.base'</Sequence>
                     </SubSequence>
                  </ByteSequence>
               </InternalSignature>
            </InternalSignatureCollection>
         </BinarySignatures>
      </File>
      <File>
         <Path>content.xml</Path>
         <BinarySignatures>
            <InternalSignatureCollection>
               <InternalSignature Id="323">
                  <ByteSequence Reference="Absolute from BOF">
                     <SubSequence Position="1" SubSeqMaxOffset="128" SubSeqMinOffset="0">
                        <Sequence>'office:document-content'</Sequence>
                     </SubSequence>
                  **</ByteSequence>
               </InternalSignature>
            </InternalSignatureCollection>
         </BinarySignatures>
         <BinarySignatures>
            <InternalSignatureCollection>
               <InternalSignature Id="323">
                  <ByteSequence Reference="Absolute from BOF">**
                     <SubSequence Position="2" SubSeqMaxOffset="" SubSeqMinOffset="0">
                        <Sequence>'office:version=' [22 27] '1.0' [22 27]</Sequence>
                     </SubSequence>
                  </ByteSequence>
               </InternalSignature>
            </InternalSignatureCollection>
         </BinarySignatures>
      </File>
   </Files>
</ContainerSignature>
```

but this is what is in the handcrafted XML:

>     <ContainerSignature Id="9000" ContainerType="ZIP">
>       <Description>Open Document Database 1.0</Description>
>       <Files>
>         <File>
>           <Path>META-INF/manifest.xml</Path>
>           <BinarySignatures>
>             <InternalSignatureCollection>
>               <InternalSignature ID="322">
>                 <ByteSequence Reference="BOFoffset">
>                   <SubSequence Position="1" SubSeqMinOffset="0"
>                     SubSeqMaxOffset="1024">
>                     <Sequence>'manifest:media-type="application/vnd.oasis.opendocument.base'</Sequence>
>                   </SubSequence>
>                 </ByteSequence>
>               </InternalSignature>
>             </InternalSignatureCollection>
>           </BinarySignatures>
>         </File>
>         <File>
>           <Path>content.xml</Path>
>           <BinarySignatures>
>             <InternalSignatureCollection>
>               <InternalSignature ID="323">
>                 <ByteSequence Reference="BOFoffset">
>                   <SubSequence Position="1" SubSeqMinOffset="0"
>                     SubSeqMaxOffset="128">
>                     <Sequence>'office:document-content'</Sequence>
>                   </SubSequence>
>                   <SubSequence Position="2" SubSeqMinOffset="0">
>                     <Sequence>'office:version=' [22 27] '1.0' [22 27]</Sequence>
>                   </SubSequence>
>                 </ByteSequence>
>               </InternalSignature>
>             </InternalSignatureCollection>
>           </BinarySignatures>
>         </File>
>       </Files>
> </ContainerSignature>

Need to write some smarter XSL to eliminate the superfluous interior tags.

**Comment by peterjohnlawrence** [comment]
Fixed, with horrendous XSL
